version: "3"
services:
  reverse-proxy:
    image: traefik:v2.2
    command: --api.insecure=true --providers.docker
    networks:
      - executeit
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock

    command: >
      sh -c "yarn dev"
    environment:
      - NODE_ENV=dev
      - PORT=5000
      - TRAEFIK_HOST=localhost
      - DOCKER_SOCKET=/var/run/docker.sock
      - USER_SERVER_IMAGE=user-image
      - USER_SERVER_CPU_LIMIT=10
      - USER_SERVER_MEM_LIMIT=256000
      - USER_SERVER_NETWORK=executeit
      - MONGO_HOST=mongo
      - MONGO_DB_NAME=executeit
      - MONGO_USER=root
      - MONGO_PASSWORD=example
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
networks:
  executeit:
    external:
      name: executeit